### ISSUE TITLE
Where to download?

### ISSUE THREAD

**Issue by Nobeernogman** [danielnilsson9/bbshd-fw#16]
Edit: After a few hours i managed to create the hex fw file and created the FW tool!
My PAS is still dead, what on earth can it be..
I just reverted my 1.4 MCU: STC15W4K56S4 back to original with CRR10E4830E104001.1.hex firmware. There is firmware available for the STC15W4K56S4  mcu.

I will try your opensource fw again in a few days! Thanks. so much fun!

-------
Hi,
I have a 1. 4 bbshd controller with some issues. Pedal assist is dead, throttle works fine.
Is your custom fw only available from build for your scratch?
I was looking for a prepped file, ready to flash :)
Kind regards!

**Comment by danielnilsson9** [comment]
Hi

I will not release any binary version until I deem it safe to use. A dangerous throttle issue is still present and I have no solution in sight.

For anyone else reading, build instructions are here:
https://github.com/danielnilsson9/bbshd-fw/wiki/Build-from-Source
