### ISSUE TITLE
Low Voltage Cutoff is handled by the ST/IAP controller or is it by the NEC chip

### ISSUE THREAD

**Issue by fang64** [danielnilsson9/bbshd-fw#18]
I'm mostly just curious if it's possible to set the LVC below 38v or does the NEC chip restrict that even in this firmware?

Thanks!

**Comment by fang64** [comment]
I think I answered my own question it appears that limit is issued by the STC/IAP chip.

**Comment by danielnilsson9** [comment]
You can set a lower LVC. It is enforced by the NEC chip but configuration is sent from STC to NEC chip on startup.
