### ISSUE TITLE
Motor power should ramp up slower

### ISSUE THREAD

**Issue by fpdragon** [danielnilsson9/bbshd-fw#5]
In the PAS modes the motor kicks in pretty hard if you start riding on a higher power level.
Currently the only way to smoth this out is to lower the PAS level before start riding and then switch back to a higher power level.

A cleaner solution would be to limit the starting power (current) while starting and then ramping the power up to the target current.

Implementation could be straight forward:

A) 
A global `target_current `tracking could be implemented. The last `target_current `shall be saved as `target_current_last `eg. If the new `target_current `is much higher than the `target_current_last `then it should be limited to a defined value.
This defined value (eg `max_current_rise`) must go hand in hand with the execution time where `target_current_last `is saved again.
Currently I don't see that the timing of the main function `app_process()` is somehow defined. It's called in an endless loop where different functions are called and has an additional 4ms delay in it so the execution period is not clearly defined and depends highly on the execution time of the functions.
Maybe there is a timer/counter that can be used to estimate the ticks that have been passed since the last target_current_last value was set? Then it would be possible to fit the `max_current_rise `to the time that has passed since the last execution.
Or the function execution time is so predictable and constant that it is good enough to just recalc in every loop call and it wont be detected.

B)
Second possibility is to limit the power kickin for PAS only. Here the function `apply_pas()` may be changed. The implementation itself could be similar to A).

**Comment by danielnilsson9** [comment]
There is an accurate timer running which is counting milliseconds since boot accessible through system_ms() so this should be quite straightforward to do.

**Comment by casainho** [comment]
On TSDZ2 our OpenSource firmware, we implement a current ramp, with configuration value done by user on the display or mobile app. This configuration is amps per second - let's say it is 10 amps per second, than we know it will take 2 seconds to increase from motor stop of 0 amps to say a 20 amps target current.

On my small kid of 8 years old, I limit the ramp current value to a kower one, for safety reasons. Also on long travels that I need to optimize my battery range, I also reduce this value.

**Comment by danielnilsson9** [comment]
> On TSDZ2 our OpenSource firmware, we implement a current ramp, with configuration value done by user on the display or mobile app. This configuration is amps per second - let's say it is 10 amps per second, than we know it will take 2 seconds to increase from motor stop of 0 amps to say a 20 amps target current.
> 
> On my small kid of 8 years old, I limit the ramp current value to a kower one, for safety reasons. Also on long travels that I need to optimize my battery range, I also reduce this value.

That sounds like a good approach, we should do the same here and add a config parameter for this value.

**Comment by fpdragon** [comment]
I just did a quick and dirty test:

```
static __xdata uint8_t last_target_current = 0;

void app_process()
{
	uint8_t target_current = 0;

	if (assist_level == ASSIST_PUSH)
	{
		if (g_config.use_push_walk)
		{
			target_current = 10;
			motor_set_target_speed(40);
		}		
	}
	else
	{
		// never limit motor rotation speed
		motor_set_target_speed(0xff);

		uint8_t throttle = throttle_read();

		apply_pas(&target_current);
		apply_cruise(&target_current, throttle);
		apply_throttle(&target_current, throttle);	
	}

	apply_speed_limit(&target_current);
	apply_thermal_limit(&target_current);

	apply_ramp_up_limit(&target_current);

	motor_set_target_current(target_current);
	
	if (target_current > 0 && !brake_is_activated())
	{
		motor_enable();
	}
	else
	{
		motor_disable();
	}
}

void apply_ramp_up_limit(uint8_t* target_current)
{
	/* if the new current exceeds the last value plus a limit */
	if (*target_current > (last_target_current + 1))
	{
		*target_current = last_target_current + 1;
	}

	// save the target_current for next fucntion call
	last_target_current = *target_current;
}
```

It runs way smoother. Maybe a little bit too smooth but it was the easiest to increment the target_current just by 1.

However I ran into an other problem that after some minutes the motor does not stop any more and ignores the pas sensor. Could be that I have made a bug but currently it's not clear for me. The first minutes it was working quite well...

**Comment by danielnilsson9** [comment]
Sounds good, yes I mean the end result will be quite similar but it would be good to be able to configure it in a unit that can be reasoned about, like amps per seconds.

Did you find the error with the motor not turning off with PAS?

**Comment by fpdragon** [comment]
> On my small kid of 8 years old, I limit the ramp current value to a kower one, for safety reasons. Also on long travels that I need to optimize my battery range, I also reduce this value.

Absolutely, and you have to keep in mind that the BBSHD has 1000W/1500W on default and I have seen it pimped with other controllers to over 3000W. It's even hard for me to keep control when starting in a curve or on a crossroad when the motor fully kicks in while leaning in the curve. And the full suspention makes it feel like I'm sitting on a boat. Even for a grown up.

But the first step is done and the easy fix above currently works for me.

**Comment by fpdragon** [comment]
I just had a long wonderful ride with the latest speed sensor fixes, my ramp up mod and some other little modifications regarding display and so on. I was driving on the street, on gravel trails and even on a small downhill trail with rocky and wood track.
The ride was awesome and the firmware works really well and I definitely stick to it and won't go back to the Bafang firmware. It works perfectly with my 15s config and shows the exact battery usage and I like the behavior of the motor.

I will test to reset the `last_target_current = 0;` when the brake sensor is detected. This could be a little improvement that the ramp up is also used after pulling the brakes.

Currently i am incrementing the current by 1 each loop execution. I will also test a max rise of 2 which should ramp up faster (twice as fast as before).

For me, this firmware, with all it's improvements, is the best one. I would also contribute my changes but I think Daniel is already doing a good job in implementing clean variants of the mods. Just let me know if I can help.

**Comment by danielnilsson9** [comment]
I'm a bit puzzled to why your code seems to work, it doesn't really make sense, that should be a super fast ramp up.

The main loop is set to execute with a 4ms delay, don't know the average execution time but a guess would be 2ms.
That would mean you would ramp up from 0% to 20% in 120ms.

Target current will only be sent to motor controller every 64ms (similar to original firmware, see motor.c). I.e. could send 0%, 10% 20% which is a bad and super fast ramp.

I will have to investigate, something must be wrong in other parts of the firmware if this provides you with a slow ramp.

I must also rewrite motor.c communication because that does blocking io with the motor control mcu on the main loop giving jerky loop execution time, was intially a quick hack...

**Comment by danielnilsson9** [comment]
I check on my scope, timing looks like expected.

4ms sleep, loop execution time usually around 1ms. Every 150ms loop execution time jumps to 60ms (blocking serial read of info from motor controller MCU)...

But still, that is around 200Hz, your ramp should be way faster than you are experiencing.

You did set CPU frequency to 18MHz when flashing controller?

**Comment by fpdragon** [comment]
> I check on my scope, timing looks like expected.
> 
> 4ms sleep, loop execution time usually around 1ms. Every 150ms loop execution time jumps to 60ms (blocking serial read of info from motor controller MCU)...
> 
> But still, that is around 200Hz, your ramp should be way faster than you are experiencing.
> 
> You did set CPU frequency to 18MHz when flashing controller?

Yes, all regarding your instruction: 18,432MHz

**Comment by fpdragon** [comment]
I just can say the following:
The current limit is 15 amps
`g_config.max_current_amps = 15;`
On the pas level 9 it can take seconds until the max power is reached. So let us say 3 seconds...
In each loop execution I make a step of 1 amp. So we should have 14 loop iterations until 15 amp are reached (theoretically)
3sec / 15 iterations = about 214ms per iteration average.

So I would say that in my setup a main loop iteration takes over 200ms in average which is huge for an embedded device and such a "simple" application.

And the 200ms would also explain the screen lag for the brake sensor indicator.

**Comment by danielnilsson9** [comment]
That is wrong.

target_current is in percent [0-100], so if max current is set to 15 your code will ramp up from 0-15 amps by moving target_current from 0 to 100, i.e. 100 iterations of the main loop.

Still seems off by a large factor though.

**Comment by fpdragon** [comment]
> That is wrong.
> 
> target_current is in percent [0-100], so if max current is set to 15 your code will ramp up from 0-15 amps by moving target_current from 0 to 100, i.e. 100 iterations of the main loop.
> 
> Still seems off by a large factor though.

I see. You are totally right.

So the calc goes 
3sec / 99 iterations = 30ms at average

30ms - 4ms delay = **26ms**

Hmmm 26ms processing time seems to be much more realistic for me including serial communication and so on.

Waht do you think?

**Comment by danielnilsson9** [comment]
Yes, there I definitely something wrong there, as my controller is consistent on 1ms processing time now.
I have only tested with DPC-18 display, maybe you display sends some command that is not handled and causes issues, I have no idea.

I have made a fix for the processing time going up to 60ms once every 150ms but there must be something more in your case. But your should try it at least I think.

**Comment by fpdragon** [comment]
> Yes, there I definitely something wrong there, as my controller is consistent on 1ms processing time now.
> I have only tested with DPC-18 display, maybe you display sends some command that is not handled and causes issues, I have no idea.
> 
> I have made a fix for the processing time going up to 60ms once every 150ms but there must be something more in your case. But your should try it at least I think.

Ok, I have to look into your code changes and merge it with my code base to be compatible.
You could be right that this is just in combination with my display...

In the end a clean solution should use a tick counter to track the time difference to the last loop exection. Then it would be possible to implement this regardless to the processing time of the main loop.

Do you already have set up a tick counter for an other purpose that may be reused for this?

**Comment by danielnilsson9** [comment]
a millisecond counter is available for this purpose, system_ms()

**Comment by fpdragon** [comment]
I think it would be much more easy if you would allow me to contribute to the repo. I could work on my own branch and you could decide what to take.

**Comment by danielnilsson9** [comment]
I think you can do that. The standard way is that you make a fork, make a new branch for your changes, commit them and then send me a pull request when you are happy.

https://jarv.is/notes/how-to-pull-request-fork-github/

**Comment by fpdragon** [comment]
```
"C:\Program Files\Git\bin\git.exe" push -u --recurse-submodules=check --progress "origin" refs/heads/f_SlowPowerRampUpHack:refs/heads/f_SlowPowerRampUpHack
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/danielnilsson9/bbshd-fw.git/'
Done

Press Enter or Esc to exit...
```

**Comment by fpdragon** [comment]
I have finished my implementation of the system_ms ramp up but I am having troubles in pushing the code

**Comment by danielnilsson9** [comment]
You will not be able to push directly to my repo, you will have work in your own fork and then submit a pull request through github

**Comment by fpdragon** [comment]
Ok, so a fork is not a branch xD

**Comment by fpdragon** [comment]
```
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Done
```

I guess I have to learn how to use GitHub first xD

**Comment by danielnilsson9** [comment]
Make sure your git version is not very old if you have authentication issues. In what context do you get this error?

**Comment by fpdragon** [comment]
ok, finally I think I have made it on my personal fork called 
`https://github.com/fpdragon/bbshd-fw.git`

**Comment by fpdragon** [comment]
I just tried to merge my code with your latest code canges and now I get again this stack problem from the linker.
Any idea how to track this down?
Why is the stack so extremly small on this device?

**Comment by danielnilsson9** [comment]
It is an ancient architecture with a 127 byte fixed stack size. Very hard to do any calculations without running out of stack.
Although there is a decent sized RAM it cannot be used for stack in the small memory model.
I have tried switch to medium or large memory model but not been able to produce a working binary.

Some tips:
* Minimize use of local variables
* Reuse local variables if possible
* Put static globals on xdata
* Put large locals on xdata (> 2bytes) e.g. int32_t
* Avoid float calculations, software routines, uses a lot of stack memory
* Pass pointers with memory types in functions (saves 1 byte)

**Comment by fpdragon** [comment]
Ok... 
I just added an other function without additional function nesting and only one local variable.
no chance... :-(

**Comment by danielnilsson9** [comment]
Yes, it's hard. It has been right on the limit for a long time...

**Comment by fpdragon** [comment]
No idea where to start...
My code itself was linking.
Your code itself was linking.
Alltogether... nope...

If we could see somehow where the stack gets to big. In which function or module...

**Comment by fpdragon** [comment]
Haha...
Due to the merge I had to change this line
`uint8_t current_limits[9] = { 25, 34, 43, 51, 60, 68, 74, 82, 90 };`
again to this
`static __xdata uint8_t current_limits[9] = { 25, 34, 43, 51, 60, 68, 74, 82, 90 };`

Now the first merge builds again xD

**Comment by fpdragon** [comment]
but still... the merge with your code fails.
and I don't see where to optimize...

**Comment by danielnilsson9** [comment]
freed up a couple more bytes, maybe it could be enough for you, checkout my branch "optimize".
stack space is only 134 bytes (see file main.mem). I think there is 12 bytes available now.

**Comment by fpdragon** [comment]
How can I get your latest changes into my fork repo? xD

**Comment by fpdragon** [comment]
Ah I think I found it myself...
Is it "Add upstream remote" ?
I guess so because now I see your changes xD

**Comment by fpdragon** [comment]
nice. it builds :-)

I merged everything in my fork repo.

Btw, sticked to "shift" sensors instead of "gear" sensors since the sensor can't read the gear number, it just senses shifting.
Hope you are fine with it.

As said, you should find the SoftLowVoltageProtection (untested) and the SlowPowerRampUp inside my master branch.

I would love to hear your opinion.

**Comment by danielnilsson9** [comment]
Looking at your code we might need another approach next time we run out of stack space because thats big calculations involving large data types which will require quite a bit of stack space. 

My idéa of doing this would have been to precompute the interval of which to increment with 1 based on the configured A/sec. 
This could be done in app_init() and would then be outside the app_process() call tree. Then you would just need to check if this time has elapsed and do the increment. It's doesn't have to be exact either, fairly close is enough.

It was called gear sensor for consistency since that what was printed on PCB but it guess it's alright, doesn't really matter, maybe should update the documentation on wiki though. :)

**Comment by fpdragon** [comment]
> Looking at your code we might need another approach next time we run out of stack space because thats big calculations involving large data types which will require quite a bit of stack space.
> 
> My idéa of doing this would have been to precompute the interval of which to increment with 1 based on the configured A/sec.
> This could be done in app_init() and would then be outside the app_process() call tree. Then you would just need to check if this time has elapsed and do the increment. It's doesn't have to be exact either, fairly close is enough.
> 
> It was called gear sensor for consistency since that what was printed on PCB but it guess it's alright, doesn't really matter, maybe should update the documentation on wiki though. :)

Cool I am open to learn :-)

And regarding gear and shift... Chinese auto translate? ;-)
It's up to you how you want to call it. I just wanted to explain my merge but it's not so important for me if you prefere the doc consistent variant I am also totaly fine with it. However I bought it as a shift sensor I think. xD

**Comment by fpdragon** [comment]
motor ramp up implemented and tested successfully.
can be found in my personal fork in the branch "`f_Lays_StableBranch`"

**Comment by danielnilsson9** [comment]
I will leave this open until a pull request is merged in this repo

**Comment by danielnilsson9** [comment]
Shall be configurable from config tool as ramp up in amps per second.
