### ISSUE TITLE
target_speed is max 250 not 255

### ISSUE THREAD

**Issue by dav0000000** [danielnilsson9/bbshd-fw#50]
Minor issue but I believe the value should be 250 not 255.

app.c
motor_set_target_speed((uint8_t)((250u * assist_level_data.max_cadence_percent) / 100u));

EventLogEntry.cs
				case EVT_DATA_TARGET_SPEED:
					return $"Motor target speed changed to {_data * 100 / 250}%.";

**Comment by danielnilsson9** [comment]
Yes, I think you are right, this has been bugging me for a while but not enough to check it. The maximum "speed" setting the motor MCU firmware seems to accept is 250, a very strange number. I send 255 and it responds that it accepted 250.
